project:
  type: website
  output-dir: docs/
  
website:
  title: "Kinlie Gohl Website"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: project.qmd
      - text: "CV"
        href: Gohl, Kinlie_Curriculum_Vitae.pdf
      - text: "Reflections"
        menu: 
          - href: Breiman and Shmueli.qmd
            text: Breiman and Shmueli Comparison
          - href: AI and Originality.qmd
            text: AI and Originality
          - href: Using AI in Projects.qmd
            text: Using AI in Projects
      - text: Assignments
        menu:
          - href: assignment1.qmd
            text: Assignment 1
          - href: Assignment 2.pdf
            text: Assignment 2
          - href: assignment3.qmd
            text: Assignment 3
format:
  html:
    theme:
      - pulse
      - brand
    css: styles.css
    toc: true

editor: visual

