project:
  type: website

website:
  title: "My Quarto Website"
  navbar:
    left:
     -  text: "Home"
        href: index.html
     -  text: "About"
        href: about.html
     -  text: "Research"
        href: teaching.html
     -  text: "CV"
        href: cv.pdf
     -  text: "Projects"
        href: _quarto.yml
format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true

editor: visual

