project:
  type: website

website:
  title: "kinliegohl.github.io"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: project.qmd
      - text: "CV"
        href: Gohl, Kinlie_Curriculum_Vitae.pdf
      - text: Assignments
        menu:
          - href: assignment1.qmd
            text: assignment1
          - href: assignment2.qmd
            text: assignment2
          - href: assignment3.qmd
            text: assignment3
format:
  html:
    theme:
      - pulse
      - brand
    css: styles.css
    toc: true

editor: visual

